@rootURL = http://localhost:8000
#API list


### Check Server Status
GET {{rootURL}}



### Auth API

### Post New User
POST {{rootURL}}/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "z@a.com",
    "phone": "528491",
    "password": "hello"
}
